const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = {window: {}, document: {documentElement: {lang:'en'}}, structuredClone, console, URL};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../ai2apps/web/static/js/imagine_studio.js','utf8'), ctx);
const app = ctx.window.imagineStudioApp();
app.miniAppId = 'ai2apps.imagine.portrait';
app.icons = () => {};
app.scheduleDraftSave = () => {};
assert.equal(app.currentMiniApp.name, 'Portrait');
assert.equal(app.requiredOperation, 'image_edit');
assert.equal(app.prefersOpenAIModel, true);
app.models = [
    {id:'one', operations:['image_edit'], referenceLimits:{minimum:1,maximum:1}},
    {id:'cloud/ai2apps/openai/gpt-image-2', source:'cloud', operations:['image_edit'], referenceLimits:{minimum:1,maximum:4}},
];
app.modelId = 'cloud/ai2apps/openai/gpt-image-2';
Object.defineProperty(app,'sizeError',{value:''});
assert.equal(app.canGenerate, false);
app.referenceFiles = [{name:'person.png'}];
assert.equal(app.canGenerate, true, 'preset portrait needs no free-form prompt');
assert.equal(app.referenceSlotCount, 1);
Object.defineProperty(app, 'selectedStyle', {value:{prompt:'STYLE_SENTINEL'}});
assert.doesNotMatch(app.composedPrompt(), /STYLE_SENTINEL/);
assert.match(app.composedPrompt(), /Photo-ID-style/);
app.portraitBackground = 'blue';
app.portraitClothing = 'suit';
assert.match(app.composedPrompt(), /solid blue background/);
assert.match(app.composedPrompt(), /business suit/);
app.portraitClothing = 'custom';
assert.equal(app.referenceSlotCount, 2);
assert.equal(app.canGenerate, false, 'Custom outfit reference is required');
assert.equal(app.compatibleModels.length, 1, 'one-reference models excluded');
app.referenceFiles[1] = {name:'clothes.png'};
assert.equal(app.canGenerate, true);
assert.match(app.composedPrompt(), /Image 2 is CLOTHING ONLY/);
assert.match(app.composedPrompt(), /Never copy the face/);
app.referenceFiles[0] = null;
assert.equal(app.canGenerate, false, 'clothes alone cannot become identity reference');
app.referenceFiles[0] = {name:'person.png'};
app.portraitMode = 'cover';
assert.match(app.composedPrompt(), /Do not render any text/);
app.portraitCoverTitle = 'MY COVER';
app.portraitCoverMood = 'classic';
app.portraitFraming = 'half';
assert.match(app.composedPrompt(), /MY COVER/);
assert.match(app.composedPrompt(), /black-and-white/);
assert.match(app.composedPrompt(), /STYLE_SENTINEL/);
app.portraitMode = 'lifestyle';
app.portraitScene = 'beach';
app.portraitLight = 'golden';
app.portraitPose = 'Sitting comfortably';
assert.match(app.composedPrompt(), /seaside beach/);
assert.match(app.composedPrompt(), /golden-hour/);
assert.match(app.composedPrompt(), /Sitting comfortably/);
assert.doesNotMatch(app.composedPrompt(), /MY COVER/);
const draft = app.draftPayload();
app.restorePortraitDraft({});
assert.equal(app.portraitMode, 'id');
app.restorePortraitDraft(draft);
assert.equal(app.portraitMode, 'lifestyle');
assert.equal(app.portraitClothing, 'custom');
assert.equal(app.portraitPose, 'Sitting comfortably');
app.portraitClothing = 'keep';
app.reconcileSelectedModel = () => {};
app.portraitClothingChanged();
assert.equal(app.referenceFiles[1], null);
assert.equal(app.referenceSlotCount, 1);
app.restorePortraitDraft({portraitMode:'invalid',portraitCoverTitle:'x'.repeat(200),portraitPose:'x'.repeat(3000)});
assert.equal(app.portraitMode, 'id');
assert.equal(app.portraitCoverTitle.length,100);
assert.equal(app.portraitPose.length,2000);
app.setLocale('zh');
assert.equal(app.currentMiniApp.name,'人像摄影棚');
assert.equal(app.referenceSlotLabel(0),'人物参考照');
assert.equal(app.referenceSlotLabel(1),'服装参考图');
console.log('Portrait modes, references, drafts and model compatibility: passed');

(async () => {
    ctx.FileReader = class {
        readAsDataURL(file) { this.result = 'data:image/png;base64,' + file.name; this.onload(); }
    };
    ctx.window.confirm = () => true;
    app.saveDraft = async () => {};
    app.createRun = async () => ({id:'portrait-test',status:'queued'});
    app.selectRun = () => {};
    app.waitForRun = async () => ({id:'portrait-test',status:'succeeded'});
    app.dismissNotice = () => {};
    app.fail = error => { throw error; };
    let payload;
    app.executeCloudRun = async (_, value) => { payload = value; };
    app.referenceFiles = [{name:'person'}, {name:'outfit'}];
    app.portraitClothing = 'keep';
    await app.generate();
    assert.deepEqual(Array.from(payload.imageDataUrls), ['data:image/png;base64,person']);
    app.portraitClothing = 'custom';
    await app.generate();
    assert.deepEqual(Array.from(payload.imageDataUrls), ['data:image/png;base64,person','data:image/png;base64,outfit']);
    assert.match(payload.prompt, /Image 2 is CLOTHING ONLY/);
    console.log('Portrait cloud request reference ordering and hidden-reference exclusion: passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
