const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = {window:{confirm:()=>true},document:{documentElement:{lang:'en'}},structuredClone,console,AbortController};
vm.createContext(ctx);
const source=fs.readFileSync(__dirname+'/../ai2apps/web/static/js/imagine_studio.js','utf8');
const template=fs.readFileSync(__dirname+'/../ai2apps/web/templates/system_apps/imagine_studio.html','utf8');
const generateBlock=template.indexOf('class="vs-submit is-generation-submit"');
const generateButton=template.indexOf('@click="generate()"',generateBlock);
const promptEditor=template.indexOf('class="is-submitted-prompt"',generateBlock);
assert.ok(generateBlock>=0 && generateButton>generateBlock && promptEditor>generateButton);
assert.match(template.slice(generateButton,promptEditor), /<\/button><\/div>\s*<section $/);
vm.runInContext(source,ctx);
const app=ctx.window.imagineStudioApp();
app.scheduleDraftSave=()=>{};app.icons=()=>{};
app.prompt='A panda';
assert.equal(app.submissionPrompt,app.composedPrompt());
app.editSubmissionPrompt('Exact manual text\nwith whitespace ');
assert.equal(app.submissionPrompt,'Exact manual text\nwith whitespace ');
const saved=app.draftPayload();
assert.equal(saved.promptOverride.text,app.submissionPrompt);
app.prompt='A cat';
assert.equal(app.submissionPrompt,app.composedPrompt());
app.syncSubmissionPrompt();
app.prompt='A panda';
assert.equal(app.promptIsEdited,false,'old manual edits must not reappear');
app.promptOverride=saved.promptOverride;
assert.equal(app.promptIsEdited,true);
app.setLocale('zh');
assert.equal(app.promptIsEdited,true,'UI locale is not a model parameter');
app.size='1024x1536';
app.syncSubmissionPrompt();
assert.equal(app.promptIsEdited,false);
app.editSubmissionPrompt('');assert.equal(app.submissionPromptValid,false);
app.editSubmissionPrompt('x'.repeat(32001));assert.equal(app.submissionPromptValid,false);
app.resetSubmissionPrompt();assert.equal(app.submissionPromptValid,true);
app.miniAppId='ai2apps.imagine.portrait';
app.editSubmissionPrompt('portrait override');
app.portraitBackground='blue';
app.syncSubmissionPrompt();
assert.match(app.submissionPrompt,/blue background/);
app.editSubmissionPrompt('temporary restore');
app.restoringPrompt=true;app.portraitBackground='red';app.syncSubmissionPrompt();
assert.ok(app.promptOverride,'do not discard override while references restore');
app.restoringPrompt=false;app.syncSubmissionPrompt();assert.equal(app.promptOverride,null);

(async()=>{
    for(const provider of ['cloud','local']) {
        const a=ctx.window.imagineStudioApp();
        a.scheduleDraftSave=()=>{};a.icons=()=>{};a.dismissNotice=()=>{};
        a.prompt='Base';a.models=[{id:'test',label:'Test',source:provider,operations:['image_generation']}];a.modelId='test';
        Object.defineProperty(a,'sizeError',{value:''});
        a.editSubmissionPrompt('MODEL PAYLOAD\nexact ');
        let input,request;
        a.saveDraft=async()=>{a.prompt='Changed during upload';};
        a.createRun=async(value)=>{input=value;return{id:'run',status:'queued'};};
        a.selectRun=()=>{};a.executeCloudRun=async(_,value)=>{request=value;};
        a.waitForRun=async()=>({id:'run',status:'succeeded'});
        a.updateRun=async()=>({id:'run',status:'succeeded'});
        a.persistResult=async()=>({});a.refreshRuns=async()=>{};
        a.fail=e=>{throw e;};
        ctx.fetch=async(_,options)=>{request=JSON.parse(options.body);return {ok:true,json:async()=>({image:{dataUrl:'data:image/png;base64,AA==',size:'1024x1024'}})};};
        await a.generate();
        assert.equal(request.prompt,'MODEL PAYLOAD\nexact ',provider);
        assert.equal(input.submittedPrompt,request.prompt,'run records exact submitted prompt');
    }
    assert.equal((source.match(/prompt: submittedPrompt, size: requestedSize/g)||[]).length,2);
    console.log('Submitted prompt editing, invalidation, draft metadata and exact cloud/local payload: passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
