const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const prefix = 'ai2apps.audio.';
const projects = [
  {id: 'quick', miniAppId: prefix + 'quick-read', segments: []},
  {id: 'book', miniAppId: prefix + 'audiobook', segments: []},
  {id: 'drama', miniAppId: prefix + 'ensemble-drama', segments: []},
];
const drafts = {};
const context = {
  window: {location: {origin: "http://localhost"}}, File: class File { constructor(parts, name, options) { this.name=name; this.type=options.type; } }, document: {querySelector: () => ({dataset: {appInstanceId: 'test'}})},
  localStorage: {setItem() {}}, clearTimeout, setTimeout, AbortController,
  fetch: async (url, options) => {
    const route = url.replace('/v1/platform/readaloud', '');
    let result;
    if (route.startsWith('/drafts/')) {
      const id = decodeURIComponent(route.slice(8));
      if (options.method === 'PUT') drafts[id] = JSON.parse(options.body).draft;
      result = {draft: drafts[id] || {}};
    } else if (route === '/projects' && options.method === 'POST') {
      const body = JSON.parse(options.body);
      result = {id: 'created', miniAppId: body.mini_app_id, title: body.title, segments: []};
      projects.push(result);
    } else if (route === '/projects') result = {items: projects};
    else if (route.startsWith('/projects/')) result = projects.find(p => p.id === route.slice(10));
    else result = {items: []};
    return {ok: true, json: async () => result};
  },
};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../ai2apps/web/static/js/readaloud.js'), 'utf8'), context);
(async () => {
  const app = context.window.readAloudApp();
  app.icons = app.emitBridge = app.success = () => {};
  app.fail = error => { throw error; };
  app.projects = projects;
  app.pipelineMode = 'audiobook';
  await app.restoreProject();
  assert.equal(app.selected.id, 'book');
  app.projectForm.title = 'Book draft';
  assert.equal(app.miniApps.some(item=>item.id===prefix+'ensemble-drama'),false);
  assert.equal(app.miniApps.find(item=>item.id===prefix+'voice-design').icon,'users-round');
  assert.equal(app.currentProjects.some(project=>project.id==='drama'),true);
  await app.openProject('drama');
  assert.equal(app.selected.id,'drama');
  await app.selectMiniApp(prefix + 'quick-read');
  assert.equal(app.selected, null);
  app.quickForm.text = 'Hello world';
  await app.saveDraft();
  await app.selectMiniApp(prefix + 'audiobook');
  await app.selectMiniApp(prefix + 'quick-read');
  assert.equal(app.quickForm.text, 'Hello world');
  assert.equal(app.selected, null);
  app.providers = [{id: 'speech', modelType: 'audio_tts', ready: true, audioCapabilities: {tts: {named_voices: {voices: ['alice', 'bob']}}}}];
  app.selectedTtsModel = 'speech';
  app.quickForm.voice = 'bob';
  let called = 0;
  context.URL = class extends URL { static createObjectURL() { return 'blob:result'; } static revokeObjectURL() {} };
  context.fetch = async (url, options) => {
    if (url === '/v1/platform/readaloud/outputs') return {ok:true,json:async()=>({items:[{id:'audio',title:'Hello',mediaType:'audio/wav',status:'succeeded',downloadUrl:'/v1/platform/sessions/session/artifacts/audio/download'}]})};
    assert.equal(url, '/v1/platform/readaloud/quick-read');
    const body = JSON.parse(options.body);
    assert.equal(body.text, 'Hello world');
    assert.equal(body.voice, 'bob');
    assert.equal(body.projectId, undefined);
    called++;
    return {ok: true, headers: {get: () => '/v1/platform/sessions/session/artifacts/audio/download'}, blob: async () => ({size: 20})};
  };
  app.scheduleDraft = () => {};
  app.$nextTick = callback => callback();
  let played = false;
  app.$refs = {audioPlayer: {play: async () => { played = true; }}};
  await app.generateQuickRead();
  assert.equal(called, 1);
  assert.equal(app.quickTasks.length, 1);
  assert.equal(app.quickTasks[0].status, 'succeeded');
  const firstTask = app.quickTasks[0];
  assert.equal(app.quickAudioUrl, 'blob:result');
  assert.equal(app.outputAudioUrl, '/v1/platform/sessions/session/artifacts/audio/download');
  app.previewAudioBlob={type:'audio/wav'};app.previewAudioBlobUrl=app.outputAudioUrl;
  assert.equal(app.quickDownloadUrl, '/v1/platform/sessions/session/artifacts/audio/download');
  app.quickDownloadFormat = 'mp3';
  assert.equal(app.quickExportUrl, '/v1/platform/sessions/session/artifacts/audio/download?audio_format=mp3');
  assert.equal(app.outputStatus, 'succeeded');
  assert.equal(app.mobilePanel, 'output');
  assert.equal(app.rightCollapsed, false);
  app.pipelineMode = 'audiobook';
  assert.notEqual(app.outputAudioUrl, 'blob:result');
  app.pipelineMode = 'quick';
  const dragData = {}; const dragFiles = [];
  app.dragPreviewAudio({dataTransfer: {setData: (key,value) => { dragData[key]=value; }, items: {add: file => dragFiles.push(file)}}, preventDefault() { throw Error('Drag unexpectedly rejected'); }});
  assert.equal(JSON.parse(dragData['application/x-ai2apps-audio-artifact']).artifactId, 'audio');
  assert.equal(dragFiles[0].type, 'audio/wav');
  assert.equal(played, true);
  assert.equal(app.quickGenerating, false);
  for (const mode of ['quick','voice','training','audiobook']) {
    app.pipelineMode=mode;
    assert.equal(app.outputAudioUrl, '/v1/platform/sessions/session/artifacts/audio/download');
    assert.equal(app.audioTasks[0].id,'audio');
  }
  app.packageMiniAppId='ai2apps.media-voice.source-separation';
  assert.equal(app.outputAudioUrl, '/v1/platform/sessions/session/artifacts/audio/download');
  app.packageMiniAppId='';app.pipelineMode='quick';
  await app.generateQuickRead();
  assert.equal(app.quickTasks.length, 2);
  app.selectQuickTask(firstTask);
  assert.equal(app.selectedQuickTaskId, firstTask.id);
  assert.equal(app.outputStatus, 'succeeded');
  app.quickForm.text = '   ';
  await app.generateQuickRead();
  assert.equal(called, 2);
  app.voiceProfiles=[{id:'character-one',name:'Alice',modelId:'speech'}];
  app.quickForm.voice='character:character-one';app.quickActorChanged();
  assert.equal(app.quickCharacter.name,'Alice');assert.equal(app.quickProvider.id,'speech');
  app.quickForm.text='Character speech';
  context.fetch=async(url,options)=> {
    if(url.endsWith('/outputs'))return {ok:true,json:async()=>({items:[]})};
    const body=JSON.parse(options.body);assert.equal(body.voice_profile_id,'character-one');assert.equal(body.voice,null);
    return {ok:true,headers:{get:()=>'/v1/platform/sessions/session/artifacts/audio/download'},blob:async()=>({size:20})};
  };
  await app.generateQuickRead();
  const asrApp=context.window.readAloudApp();
  asrApp.providers=[{id:'recognizer',modelType:'audio_stt',ready:true}];
  asrApp.saveDraft=async()=>{};asrApp.scheduleDraft=asrApp.icons=asrApp.success=()=>{};
  asrApp.fail=error=>{throw error};asrApp.finishCapability=async()=>{};
  context.window.AI2AppsCapabilities={ensure:async(request,options)=>{
    assert.equal(request.capability,'audio.speech_recognition');
    assert.equal(request.requirements.modelId,undefined);assert.equal(options.installMore,true);
    return {provider:{modelId:'recognizer'}};
  }};
  await asrApp.selectQuickAsrModel({target:{value:'__install_more__'}});
  assert.equal(asrApp.quickForm.asrModelId,'recognizer');assert.equal(asrApp.configuringQuickAsr,false);
  await asrApp.selectQuickAsrModel({target:{value:''}});
  assert.equal(asrApp.quickForm.asrModelId,'');
  const restored = context.window.readAloudApp();
  restored.icons = () => {};
  restored.selectedQuickTaskId = 'old';
  context.fetch = async () => ({ok: true, json: async () => ({items: [
    {id:'new', title:'New', status:'succeeded', url:'/new/download', downloadUrl:'/new/download'},
    {id:'old', title:'Old', status:'succeeded', url:'/old/download', downloadUrl:'/old/download'},
  ]})});
  await restored.refreshQuickHistory();
  assert.equal(restored.quickTasks.length, 2);
  assert.equal(restored.quickAudioTitle, 'Old');
  await restored.refreshOutputs('/old/download');
  assert.equal(restored.outputAudioTitle, 'Old');
  assert.equal(restored.quickDownloadUrl, '/old/download');
  restored.selectedQuickTaskId = 'missing'; restored.quickDownloadUrl = '';
  await restored.refreshQuickHistory();
  assert.equal(restored.quickAudioTitle, 'New');
  await restored.refreshOutputs();
  assert.equal(restored.outputAudioTitle, 'Old');
  const characters = context.window.readAloudApp();
  characters.icons = () => {};
  characters.scheduleDraft = () => {};
  characters.beginCharacter();
  assert.equal(characters.showVoiceForm, true);
  assert.equal(characters.currentMiniApp.id, 'ai2apps.audio.voice-design');
  characters.setCharacterMode('training');
  assert.equal(characters.currentMiniApp.id, 'ai2apps.audio.voice-design');
  assert.equal(characters.draftPayload().characterMode, 'training');
  assert.equal(characters.miniApps.some(item => item.id === 'ai2apps.audio.character-training'), false);
  characters.closeCharacterForm();
  assert.equal(characters.showVoiceForm, false);
  assert.equal(characters.pipelineMode, 'voice');
  const training = context.window.readAloudApp();
  training.scheduleDraft = () => {}; training.icons = () => {};
  training.providers = [{id:'clone',ready:true,trainingRequirements:{method:'reference',minSamples:1,maxSamples:1,transcript:'required',executable:true}}];
  Object.assign(training.trainingForm,{modelId:'clone',name:'Character',consentConfirmed:true,usageRightsConfirmed:true,antiImpersonationAcknowledged:true});
  training.addTrainingSample({id:'a',name:'One.wav'});
  training.addTrainingSample({id:'b',name:'Two.wav'});
  assert.equal(training.trainingSamples.length,2);
  assert.equal(training.selectedTrainingSamples.length,2);
  training.trainingSamples[1].selected=false;
  assert.equal(training.trainingCanPreview,false);
  training.trainingSamples[0].transcript='Hello';
  assert(training.trainingPreviewIssues.includes('readaloud.training.confirm_needed'));
  training.trainingSamples[0].confirmed=true;
  assert.equal(training.trainingCanPreview,true);
  training.voiceProfiles=[{sourceType:'synthetic_designed',referenceAssetId:'a',training:{samples:[{asset_id:'a'}]}},{sourceType:'synthetic_designed',training:{design:{}}}];
  assert.equal(training.trainedVoices.length,1);
  training.trainingSamples[1].selected=true;
  assert.equal(training.trainingCanSave,true);
  assert.equal(training.trainingMergesSamples,true);
  assert.equal(training.trainingCanPreview,false);
  training.trainingSamples[1].selected=false;
  const reopened = context.window.readAloudApp(); reopened.applyDraft(training.draftPayload());
  assert.equal(reopened.trainingSamples.length,2);
  assert.equal(reopened.trainingSamples[0].confirmed,true);
  assert.equal(reopened.trainingForm.modelId,'clone');
  training.removeTrainingSample(training.trainingSamples[1]);
  assert.equal(training.trainingSamples.length,1);
  context.FormData = class { append() {} };
  training.providers.push({id:'asr',modelType:'audio_stt',ready:true});
  training.ensureCapability = async () => ({});
  const sample = training.trainingSamples[0];
  let resolveAsr, started;
  const asrStarted = new Promise(resolve => { started=resolve; });
  context.fetch = async url => url.includes('/content') ? {ok:true,blob:async()=>({})} : {ok:true,json:async()=> {started(); return new Promise(resolve => {resolveAsr=resolve;});}};
  const pendingAsr=training.transcribeTrainingSample(sample);
  await asrStarted;
  sample.transcript='Manual edit'; sample.confirmed=false;
  resolveAsr({text:'ASR result'}); await pendingAsr;
  assert.equal(sample.transcript,'Manual edit');
  assert.equal(sample.confirmed,false);
  context.fetch = async url => url.includes('/content') ? {ok:true,blob:async()=>({})} : {ok:false,json:async()=>({detail:'ASR unavailable'})};
  await training.transcribeTrainingSample(sample);
  assert.equal(sample.state,'failed');
  assert.equal(sample.transcript,'Manual edit');
  const rawSample={assetId:'auto-recorded',name:'recording.webm',transcript:'',confirmed:false,state:'idle'};
  const reactiveWrites=[];
  const reactiveSample=new Proxy(rawSample,{set(target,key,value){reactiveWrites.push([key,value]);target[key]=value;return true;}});
  training.trainingSamples=[reactiveSample];
  context.fetch=async url=>url.includes('/content')?{ok:true,blob:async()=>({})}:{ok:true,json:async()=>({text:'Finished transcription'})};
  await training.transcribeTrainingSample(rawSample);
  assert(reactiveWrites.some(([key,value])=>key==='state'&&value==='idle'));
  assert(reactiveWrites.some(([key,value])=>key==='transcript'&&value==='Finished transcription'));
  assert.equal(training.voiceWaitKind,'');
  const realSetTimeout=context.setTimeout;
  context.setTimeout=callback=>realSetTimeout(callback,0);
  context.fetch=async (url,options)=>new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted'))));
  await training.transcribeTrainingSample(rawSample);
  context.setTimeout=realSetTimeout;
  assert.equal(rawSample.state,'failed');
  assert.match(rawSample.error,/timed out/);
  assert.equal(training.voiceWaitKind,'');
  const design = context.window.readAloudApp();
  design.providers = [
    {id:'base',modelType:'audio_tts',capabilities:['voice_cloning']},
    {id:'custom',modelType:'audio_tts',capabilities:['voice_instructions','named_voices']},
    {id:'design',modelType:'audio_tts',capabilities:['voice_design','voice_instructions']},
  ];
  assert.equal(design.voiceDesignProviders.length,1);
  assert.equal(design.voiceDesignProviders[0].id,'design');
  design.voiceForm.modelId='custom'; design.normalizeVoiceDesignBinding();
  assert.equal(design.voiceForm.modelId,'');
  design.scheduleDraft = design.icons = () => {};
  design.openVoice({id:'alice', name:'Alice', modelId:'design',referenceTranscript:'Hello',training:{design:{description:'Warm voice',preview:{download_url:'/preview.wav'}}}});
  assert.equal(design.voiceForm.profileId,'alice');
  assert.equal(design.voiceForm.description,'Warm voice');
  assert.equal(design.designPreviewUrl,'/preview.wav');
  assert.equal(design.outputAudioUrl,'');
  assert.equal(design.designCanRun,'Hello');
  design.designChanged();
  assert.equal(design.outputAudioUrl,'');
  design.trainingForm={profileId:'alice-clone',name:'Alice',modelId:'clone',sourceType:'synthetic_designed',assetId:'alice-audio',consentConfirmed:true};
  design.trainingSamples=[{assetId:'alice-audio',transcript:'Alice',confirmed:true,selected:true}];
  design.trainingPreviewUrl='/alice-preview.wav';design.trainingPreviewTitle='Alice';design.trainingPreviewStatus='succeeded';
  design.trainingPreviewText='Old Alice text';
  design.beginCharacter();
  design.setCharacterMode('training');
  assert.equal(design.trainingForm.profileId,'');
  assert.equal(design.trainingForm.name,'');
  assert.equal(design.trainingForm.modelId,'');
  assert.equal(design.trainingForm.assetId,'');
  assert.equal(design.trainingForm.sourceType,'self_voice');
  assert.equal(design.trainingForm.consentConfirmed,false);
  assert.equal(design.trainingSamples.length,0);
  assert.equal(design.outputAudioUrl,'');
  assert.equal(design.trainingPreviewTitle,'');
  assert.equal(design.outputStatus,'idle');
  assert.notEqual(design.trainingPreviewText,'Old Alice text');
  design.trainingSamples=[{assetId:'new-draft',selected:true}];
  design.setCharacterMode('voice');design.setCharacterMode('training');
  assert.equal(design.trainingSamples[0].assetId,'new-draft');
  const freshDraft=context.window.readAloudApp();freshDraft.applyDraft(design.draftPayload());
  assert.equal(freshDraft.trainingForm.profileId,'');
  assert.equal(freshDraft.trainingSamples[0].assetId,'new-draft');
  assert.equal(design.voiceForm.profileId,'');
  assert.equal(design.voiceForm.description,'');
  let configuredBody;
  context.window.AI2AppsCapabilities = {ensure:async body=>{configuredBody=body;design.providers.find(p=>p.id==='design').ready=true;return {outcome:'already_ready'};}};
  design.voiceForm.modelId='design';design.refresh=async()=>{};design.fail=error=>{throw error;};
  await design.configureDesignModel();
  assert.equal(configuredBody.capability,'audio.voice_design');
  assert.equal(configuredBody.requirements.modelId,'design');
  assert(configuredBody.requirements.operations.includes('voice_design'));
  const autoAsr=context.window.readAloudApp();
  autoAsr.scheduleDraft=()=>{};
  autoAsr.providers=[{id:'asr',modelType:'audio_stt',ready:true}];
  let automaticallyTranscribed=[];
  autoAsr.transcribeTrainingSample=sample=>automaticallyTranscribed.push(sample.assetId);
  // Optional or unselected clone models must not prevent automatic ASR.
  autoAsr.addTrainingSample({id:'recorded',name:'recording.wav'});
  assert.deepEqual(automaticallyTranscribed,['recorded']);
  autoAsr.autoTrainingAsr=false;
  autoAsr.addTrainingSample({id:'disabled',name:'disabled.wav'});
  assert.equal(automaticallyTranscribed.length,1);
  autoAsr.autoTrainingAsr=true;autoAsr.providers=[];
  autoAsr.addTrainingSample({id:'no-asr',name:'waiting.wav'});
  assert.equal(automaticallyTranscribed.length,1);
  const waiting=context.window.readAloudApp();
  assert.equal(waiting.voiceWaitKind,'');
  waiting.trainingSamples=[{name:'recording.wav',state:'running'}];
  assert.equal(waiting.voiceWaitKind,'asr');
  assert.equal(waiting.voiceWaitDetail,'recording.wav');
  waiting.trainingSamples[0].state='failed';
  assert.equal(waiting.voiceWaitKind,'');
  waiting.trainingBusy=true;
  assert.equal(waiting.voiceWaitKind,'preview');
  waiting.trainingBusy=false;waiting.designBusy=true;waiting.designStatus='running';
  assert.equal(waiting.voiceWaitKind,'preview');
  waiting.designBusy=false;
  assert.equal(waiting.voiceWaitKind,'');
  waiting.quickGenerating=true;
  assert.equal(waiting.voiceWaitKind,'preview');
  waiting.quickGenerating=false;
  assert.equal(waiting.voiceWaitKind,'');
  const removal=context.window.readAloudApp();removal.scheduleDraft=()=>{};
  removal.trainingSamples=[{assetId:'keep',name:'keep.wav'},{assetId:'remove',name:'remove.wav'}];
  removal.requestSampleRemoval(removal.trainingSamples[1]);
  assert.equal(removal.trainingSamples.length,2);
  removal.pendingSampleRemoval=null;
  assert.equal(removal.trainingSamples.length,2);
  removal.requestSampleRemoval(removal.trainingSamples[1]);removal.confirmSampleRemoval();
  assert.equal(removal.trainingSamples.length,1);
  assert.equal(removal.trainingSamples[0].assetId,'keep');
  assert.equal(removal.pendingSampleRemoval,null);
  training.trainingPreviewText='   ';
  assert.equal(training.trainingPayload().preview_text,design.voiceForm.referenceTranscript);
  training.trainingPreviewText='My own preview';
  assert.equal(training.trainingPayload().preview_text,'My own preview');
  const saver=context.window.readAloudApp();
  saver.scheduleDraft=saver.icons=saver.success=()=>{};saver.fail=error=>{throw error;};
  saver.pipelineMode='training';saver.showVoiceForm=true;
  saver.providers=[{id:'clone',ready:true,trainingRequirements:{revision:'v1',method:'reference',minSamples:1,maxSamples:1,transcript:'optional',executable:true}}];
  Object.assign(saver.trainingForm,{name:'New voice',modelId:'clone',consentConfirmed:true,usageRightsConfirmed:true,antiImpersonationAcknowledged:true});
  saver.trainingSamples=[{assetId:'ref',name:'ref.wav',selected:true,transcript:'Hello',confirmed:true}];
  saver.trainingPreviewText='Custom preview';saver.trainingPreviewUrl='/previous-preview.wav';
  const saveBodies=[];
  context.fetch=async (url,options)=>{saveBodies.push(JSON.parse(options.body));return {ok:true,json:async()=>({id:'saved-voice',name:'New voice',training:{model_revision:'v1'}})};};
  await saver.saveTrainingMaterial();
  assert.equal(saver.showVoiceForm,true);assert.equal(saver.pipelineMode,'training');
  assert.equal(saver.trainingSamples.length,1);assert.equal(saver.trainingSamples[0].confirmed,true);
  assert.equal(saver.trainingPreviewText,'Custom preview');assert.equal(saver.trainingPreviewUrl,'/previous-preview.wav');
  assert.equal(saver.trainingForm.profileId,'saved-voice');
  assert.equal(saver.trainingForm.consentConfirmed,true);
  await saver.saveTrainingMaterial();
  assert.equal(saveBodies[1].profile_id,'saved-voice');
  assert.equal(saver.voiceProfiles.length,1);
  const deleteProject=context.window.readAloudApp();
  deleteProject.icons=deleteProject.scheduleDraft=deleteProject.success=()=>{};
  deleteProject.fail=error=>{throw error;};deleteProject.restoreProject=async()=>{};
  deleteProject.projects=[{id:'delete-me',title:'Book'},{id:'keep-book',title:'Keep'}];
  deleteProject.selected=deleteProject.projects[0];deleteProject.selectedProjectId='delete-me';
  deleteProject.requestProjectRemoval();assert.equal(deleteProject.projects.length,2);
  deleteProject.pendingProjectRemoval=null;assert.equal(deleteProject.selectedProjectId,'delete-me');
  deleteProject.requestProjectRemoval();
  context.fetch=async (url,options)=>{assert.equal(url,'/v1/platform/readaloud/projects/delete-me');assert.equal(JSON.parse(options.body).status,'archived');return {ok:true,json:async()=>({})};};
  await deleteProject.confirmProjectRemoval();
  assert.equal(deleteProject.projects.length,1);assert.equal(deleteProject.projects[0].id,'keep-book');
  assert.equal(deleteProject.selected,null);assert.equal(deleteProject.pendingProjectRemoval,null);
  assert.equal(deleteProject.deletingProject,false);
  const bookAsr=context.window.readAloudApp();
  bookAsr.selected={id:'book',asrVerification:true,asrModelId:''};
  bookAsr.providers=[{id:'asr-book',modelType:'audio_stt',ready:true}];
  bookAsr.icons=()=>{};bookAsr.fail=e=>{throw e;};
  let savedAsr=0;bookAsr.saveProject=async()=>{savedAsr++;};
  bookAsr.capabilityRequest=()=>({requirements:{modelId:'old'}});
  bookAsr.finishCapability=async()=>{};
  context.window.AI2AppsCapabilities={ensure:async(request,options)=>{
    assert.equal(request.requirements.modelId,undefined);assert.equal(options.installMore,true);
    return {provider:{modelId:'asr-book'}};
  }};
  await bookAsr.selectProjectAsrModel({target:{value:'__install_more__'}});
  assert.equal(bookAsr.selected.asrModelId,'asr-book');assert.equal(savedAsr,1);
  await bookAsr.selectProjectAsrModel({target:{value:''}});
  assert.equal(bookAsr.selected.asrModelId,'');assert.equal(savedAsr,2);
  const trainingAsr=context.window.readAloudApp();
  trainingAsr.pipelineMode='training';trainingAsr.providers=[];
  trainingAsr.icons=trainingAsr.scheduleDraft=trainingAsr.success=()=>{};
  trainingAsr.fail=e=>{throw e;};trainingAsr.saveDraft=async()=>{};
  trainingAsr.capabilityRequest=()=>({requirements:{modelId:'old'}});
  trainingAsr.finishCapability=async()=>{trainingAsr.providers=[{id:'new-asr',modelType:'audio_stt',ready:true}];};
  context.window.AI2AppsCapabilities={ensure:async(request,options)=>{
    assert.equal(request.requirements.modelId,undefined);assert.equal(options.installMore,true);
    return {provider:{modelId:'new-asr'}};
  }};
  assert.equal(trainingAsr.selectedSttProvider,null);
  await trainingAsr.selectTrainingAsrModel({target:{value:'__install_more__'}});
  assert.equal(trainingAsr.trainingAsrModelId,'new-asr');
  assert.equal(trainingAsr.selectedSttProvider.id,'new-asr');
  assert.equal(trainingAsr.configuringTrainingAsr,false);
  context.window.AI2AppsCapabilities.ensure=async()=>{throw {code:'provisioning_cancelled'};};
  await trainingAsr.selectTrainingAsrModel({target:{value:'__install_more__'}});
  assert.equal(trainingAsr.trainingAsrModelId,'new-asr');
  await trainingAsr.selectTrainingAsrModel({target:{value:''}});
  assert.equal(trainingAsr.trainingAsrModelId,'');
  console.log('Voice Studio: project isolation and project-free Quick Read generation passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
