const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const text=fs.readFileSync(__dirname+'/../web/static/js/agent_mini.js','utf8');
const code=text.slice(text.indexOf('    async function restartWorkspaceEditor('),text.indexOf('    async function ensureWorkspaceBrowserContext('));
function setup(saved=false){const calls=[],nodes=new Map(),state={busy:false,recipe:{id:'recipe'},review:{},draft:{id:'draft'},attachments:[{asset_id:'image'}],context:{profile_key:'work',url:'https://example.com/',title:'example.com'},exploration:{goal:'read articles',status:'failed',pendingCall:{run_id:'child'}},run:{id:'root',status:'waiting_input'}};
 const env={state,URL,Set,encodeURIComponent,clearTimeout,location:{href:'https://local/editor?workspace_editor=1&recipe_id=recipe'+(saved?'&draft_id=draft':'')},window:{confirm:()=>true},tr:x=>x,withBusy:async f=>f(),api:async(p,o)=>{calls.push([p,o?.method||'GET']);return {status:'waiting_input'};},persistExplorationCheckpoint:async()=>calls.push(['checkpoint',state.exploration.status]),renderRun:r=>state.run=r,renderExploration(){},renderRecipeReview(){},history:{replaceState:(a,b,url)=>calls.push(['url',url])},openDraft:async id=>calls.push(['open',id]),switchMode:x=>calls.push(['mode',x]),document:{documentElement:{classList:{add(){}}}},renderAttachments(){},setContextPinned(){},notice(){},$:key=>{if(!nodes.has(key))nodes.set(key,{value:'',focus(){},scrollIntoView(){}});return nodes.get(key);}};vm.runInNewContext(code,env);return {env,state,calls,nodes};}
test('declining restart keeps edits and running tasks untouched',async()=>{const h=setup();h.env.window.confirm=()=>false;await h.env.restartWorkspaceEditor();assert.equal(h.calls.length,0);assert.equal(h.state.recipe.id,'recipe');});
test('restart cancels owned runs, invalidates checkpoint and preserves goal, attachments and Profile',async()=>{const h=setup();await h.env.restartWorkspaceEditor();assert.ok(h.calls.some(x=>x[0].endsWith('/root/cancel')));assert.ok(h.calls.some(x=>x[0].endsWith('/child/cancel')));assert.ok(h.calls.some(x=>x[0]==='checkpoint'&&x[1]==='cancelled'));assert.equal(h.state.recipe,null);assert.equal(h.state.context.profile_key,'work');assert.equal(h.state.attachments[0].asset_id,'image');assert.equal(h.nodes.get('#agent-quick-input').value,'read articles');assert.ok(!h.calls.find(x=>x[0]==='url')[1].includes('recipe_id'));});
test('saved Agent restart reopens saved draft without deleting it',async()=>{const h=setup(true);await h.env.restartWorkspaceEditor();assert.ok(h.calls.some(x=>x[0]==='open'&&x[1]==='draft'));assert.ok(!h.calls.some(x=>x[0].includes('/archive')));});
test('cancellation failure leaves editor content in place',async()=>{const h=setup();h.env.api=async()=>{throw Error('offline')};await assert.rejects(h.env.restartWorkspaceEditor(),/offline/);assert.equal(h.state.recipe.id,'recipe');});
