const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/../web/static/js/agent_mini.js','utf8');
const helpers=source.slice(source.indexOf('    let checkpointQueue'),source.indexOf('    function addExplorationEvent('));
function fixture(checkpoint){const calls=[],nodes={};const state={context:{bidi_context:'tab-a'},attachments:[]};const context={state,Promise,encodeURIComponent,$:id=>nodes[id]||=( {} ),api:async(path,options)=>{calls.push({path,options});return {checkpoint};},setContextPinned:v=>calls.push({pinned:v}),renderAttachments(){},renderExploration(){},loadRecipeReview:async()=>{},notice:(...args)=>calls.push({notice:args}),tr:x=>x};vm.runInNewContext(helpers+'\nglobalThis.restore=restoreExplorationCheckpoint;globalThis.persist=persistExplorationCheckpoint;',context);return {context,state,calls,nodes};}
test('reload restores progress, attachments and unknown in-flight action without replay',async()=>{const {context,state,calls,nodes}=fixture({version:1,exploration:{goal:'发布微博',status:'running',attempts:[{outcome:'success'}],events:[],pendingStep:{operation:'click',target:{intent:'发送'}}},attachments:[{asset_id:'a'}]});assert.equal(await context.restore(),true);assert.equal(state.exploration.status,'interrupted');assert.equal(state.exploration.attempts.length,2);assert.equal(state.exploration.attempts[1].outcome,'unknown');assert.equal(state.exploration.pendingStep,undefined);assert.equal(state.attachments[0].asset_id,'a');assert.equal(nodes['#agent-quick-input'].value,'发布微博');assert.equal(calls[0].path,'/agent-explorations/checkpoint?context=tab-a');assert.ok(calls.some(x=>x.pinned));});
test('checkpoint writes stay ordered and exclude timer handles',async()=>{const {context,state,calls}=fixture(null);state.exploration={status:'running',events:[],attempts:[],loginTimer:123};const first=context.persist();state.exploration.status='needs_user';const second=context.persist();await Promise.all([first,second]);const bodies=calls.filter(x=>x.options).map(x=>JSON.parse(x.options.body));assert.deepEqual(bodies.map(x=>x.checkpoint.exploration.status),['running','needs_user']);assert.equal(bodies[0].checkpoint.exploration.loginTimer,undefined);});
test('cancelled exploration is not restored',async()=>{const {context,state}=fixture({version:1,exploration:{status:'cancelled'}});assert.equal(await context.restore(),false);assert.equal(state.exploration,undefined);});
const bidiContext={window:{addEventListener(){}}};vm.runInNewContext(fs.readFileSync(__dirname+'/../web/static/js/browser_bidi_client.js','utf8'),bidiContext);const Client=bidiContext.window.AI2AppsBiDi.AI2AppsPageClient;
test('login redirect keeps authoritative Tab even when another Tab matches stale URL',async()=>{const c=new Client({bidi_context:'tab-a',url:'about:newtab'});c.connection={command:async()=>({contexts:[{context:'tab-a',url:'https://weibo.com/'},{context:'tab-b',url:'about:newtab'}]})};assert.equal(await c.resolveContext(),'tab-a');});
test('closed bound Tab cannot fall back to an unrelated Tab',async()=>{const c=new Client({bidi_context:'tab-a',url:'https://weibo.com/'});c.connection={command:async()=>({contexts:[{context:'tab-b',url:'https://weibo.com/'}]})};await assert.rejects(()=>c.resolveContext(),/closed or unavailable/);});
