const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '../web/static/js/studio_mini_apps.js'), 'utf8');
const fn = source.slice(source.indexOf('    function taskModelError('), source.indexOf('    async function payload('));
const context = vm.createContext({document: {documentElement: {lang: 'zh-CN'}}});
vm.runInContext(fn, context);
const format = context.taskModelError;
const missing = format({detail: {code: 'translation_not_ready', details: {purpose: 'work_standard'}}});
assert.match(missing, /标准任务/);
assert.match(missing, /保存默认设置/);
assert.match(missing, /BYOK/);
assert.match(format({detail: {code: 'translation_not_ready', details: {purpose: 'work_simple'}}}, 'en'), /Simple Task/);
assert.match(format({detail: {code: 'translation_failed', details: {upstream_status: 403}}}), /聊天可用而此处仍失败/);
assert.match(format({detail: {code: 'translation_failed', details: {upstream_status: 429}}}), /额度/);
assert.match(format({detail: {message: "{'code': 'translation_not_ready', 'message': 'No model is configured for work_standard'}"}}), /保存默认设置/);
assert.match(format({error: {code: 'http_error', message: "{'code': 'translation_failed', 'message': 'Text transformation failed with HTTP 403'}"}}), /聊天可用而此处仍失败/);
assert.equal(format({detail: {code: 'other_error', message: 'Other'}}), null);
assert.match(format({detail: {code: 'translation_failed', details: {upstream_status: 503}}}), /本地模型运行状态/);
console.log('9 task-model error cases passed');
