const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/../web/static/js/todo.js','utf8');
function setup(){const card={innerHTML:'',querySelector:()=>null};const ctx=vm.createContext({Date,JSON,Number,Math,state:{},aggregateId:null,zh:true,active:s=>s==='running',selectedId:'p',tr:k=>k,time:t=>t,esc:s=>String(s).replace(/</g,'&lt;'),$:s=>s==='#current-execution'?card:null});vm.runInContext(source.slice(source.indexOf('function runElapsed('),source.indexOf('function renderRuns(')),ctx);return {ctx,card};}
test('elapsed freezes on finish and tolerates missing times',()=>{const {ctx}=setup();assert.equal(ctx.runElapsed({status:'completed',started_at:'2026-10-04T00:00:00Z',finished_at:'2026-10-04T00:01:05Z'}),'1m 5s');assert.equal(ctx.runElapsed({status:'completed'}),'—');});
test('active run takes precedence and escapes activity; latest result remains visible',()=>{const {ctx,card}=setup();const done={status:'completed',log:'Finished',started_at:'2026-10-04T00:00:00Z'};ctx.renderCurrentRun([done,{status:'running',log:'<script>step',started_at:'2026-10-04T00:00:00Z'}]);assert.match(card.innerHTML,/currentRun/);assert.match(card.innerHTML,/&lt;script>/);ctx.renderCurrentRun([done]);assert.match(card.innerHTML,/latestRun/);assert.match(card.innerHTML,/Finished/);ctx.renderCurrentRun([]);assert.match(card.innerHTML,/runIdle/);});
test('writer conflict offers conversation change instead of retrying ownership',()=>{const {ctx,card}=setup();ctx.renderCurrentRun([{status:'failed',error:'thread existing already has an active writer'}]);assert.match(card.innerHTML,/更换会话/);assert.match(card.innerHTML,/即使暂未生成内容/);assert.doesNotMatch(card.innerHTML,/id="retry-current-run"/);});
test('Desktop owned execution exposes Desktop link rather than false local stop',()=>{const {ctx,card}=setup();ctx.renderCurrentRun([{status:'running',desktop_native:true,codex_thread_id:'abc',log:'Queued'}]);assert.match(card.innerHTML,/data-open-codex="abc"/);assert.doesNotMatch(card.innerHTML,/id="stop-current-run"/);});
test('structured result distinguishes self-report and escapes content',()=>{const {ctx,card}=setup();ctx.renderCurrentRun([{status:'ended',result_report_state:'valid',result_report:{outcome:'waiting_user',summary:'<script>x</script>',completed:['Done'],verification:['Tested'],remaining:['Choose'],question:'Which target?'}}]);assert.match(card.innerHTML,/等待用户/);assert.match(card.innerHTML,/Which target/);assert.match(card.innerHTML,/&lt;script>/);assert.match(card.innerHTML,/不会自动更改项目状态或进度/);});
test('missing result never claims task completion',()=>{const {ctx,card}=setup();ctx.renderCurrentRun([{status:'ended',result_report_state:'missing'}]);assert.match(card.innerHTML,/未收到有效的结构化结果/);assert.doesNotMatch(card.innerHTML,/AI 报告已完成/);});
test('ended execution offers review and reviewed execution removes actions',()=>{const {ctx,card}=setup();ctx.renderCurrentRun([{id:'r',status:'ended'}]);assert.match(card.innerHTML,/确认完成/);assert.match(card.innerHTML,/仍需继续/);ctx.renderCurrentRun([{id:'r',status:'ended',review:{decision:'completed',reviewed_at:'2026-10-06'}}]);assert.match(card.innerHTML,/已确认完成/);assert.match(card.innerHTML,/2026-10-06/);assert.doesNotMatch(card.innerHTML,/data-review-run/);});
