(() => {
    'use strict';
    const $ = id => document.getElementById(id);
    const mode = document.body.dataset.mode;
    const capability = mode === 'music' ? 'audio.music_generation' : 'audio.sound_effects_generation';
    const installOption = '__install_model__';
    let currentModel = '';
    const miniApp = `ai2apps.audio-generation.${mode}`;
    const messages = {
        en: {model:'Model',install:'Install model…',prompt:'Description',promptHint: mode === 'music' ? 'Describe the mood, instruments, style and rhythm.' : 'Describe the sound, surroundings and how it changes over time.',lyrics:'Lyrics (optional)',lyricsHint:'Leave blank for instrumental music. Lyrics are available with ACE-Step.',duration:'Duration (seconds)',advanced:'Advanced',seed:'Seed',steps:'Sampling steps',generate:'Generate',cancel:'Cancel',outputHint:'Listen, save and drag results from the shared Preview & Output.',connecting:'Connecting to Voice Studio…',ready:'Ready to generate.',setup:'Install a model to begin.',running:'Generating audio…',cancelled:'Generation cancelled.',complete:'Audio added to Preview & Output.',failed:'Generation failed. Please retry.',none:'Select a model',notReady:' — setup required',bounds:'{min}–{max} seconds',powered:'Powered by Stability AI. Original license terms apply.',englishPrompt:'Stable Audio is trained on English descriptions. You can write in your own language. Every generation uses your Simple Task model to translate and polish the description into English.',saving:'Preparing models…',title:mode==='music'?'Music Generation':'Sound Effects'},
        zh: {model:'模型',install:'安装模型…',prompt:'声音描述',promptHint:mode==='music'?'描述情绪、乐器、风格和节奏。':'描述声音、环境及其随时间的变化。',lyrics:'歌词（可选）',lyricsHint:'留空生成纯音乐。歌词仅适用于 ACE-Step。',duration:'时长（秒）',advanced:'高级选项',seed:'随机种子',steps:'采样步数',generate:'生成',cancel:'取消',outputHint:'在共享「预览与输出」中试听、保存和拖出结果。',connecting:'正在连接语音工坊…',ready:'可以开始生成。',setup:'安装模型后即可开始。',running:'正在生成声音…',cancelled:'已取消生成。',complete:'声音已加入预览与输出。',failed:'生成失败，请重试。',none:'选择模型',notReady:' — 需要配置',bounds:'{min}–{max} 秒',powered:'Powered by Stability AI。适用原始许可条款。',englishPrompt:'Stable Audio 使用英文描述训练。可以输入中文；系统会按原意转换比喻表达。每次生成前会调用简单 Task 模型，翻译并润色为英文。',saving:'正在配置模型…',title:mode==='music'?'音乐生成':'音效生成'}
    };
    let locale='en', port, serial=0, models=[], busy=false, cancelling=false, status='connecting';
    const pending=new Map();
    const t = (key, values={}) => (messages[locale][key] || messages.en[key] || key).replace(/\{(\w+)\}/g, (_,key)=>String(values[key]??''));
    const selected=()=>models.find(m=>m.id===$('model').value);
    function state(){ $('inputs').disabled=busy; $('generate').disabled=!port||busy||!selected()?.ready||!$('prompt').value.trim(); $('cancel').disabled=!busy||cancelling||status!=='running'; $('status').textContent=t(status); }
    function options(previous){$('model').replaceChildren(); if(!models.length)$('model').add(new Option(t('none'),''));for(const m of models)$('model').add(new Option(m.label+(m.ready?'':t('notReady')),m.id));$('model').add(new Option(t('install'),installOption));$('model').value=models.some(m=>m.id===previous)?previous:(models.find(m=>m.ready)?.id||models[0]?.id||''); modelChanged();}
    function modelChanged(){currentModel=$('model').value;const m=selected();$('lyrics-field').hidden=!m?.lyrics;$('duration').min=m?.minimumSeconds||1;$('duration').max=m?.maximumSeconds||120;if(m)$('duration').value=Math.max(m.minimumSeconds,Math.min(m.maximumSeconds,Number($('duration').value)||10));$('model-note').textContent=m?t('bounds',{min:m.minimumSeconds,max:m.maximumSeconds})+(m.id.includes('stable-audio')?' · '+t('powered'):''):t('setup');if(m?.preferredPromptLanguage==='en')$('model-note').textContent+=' '+t('englishPrompt');state();}
    function localize(value){locale=String(value||'').toLowerCase().startsWith('zh')?'zh':'en';document.documentElement.lang=locale;document.title=t('title');document.querySelectorAll('[data-text]').forEach(el=>{el.textContent=t(el.dataset.text);});options($('model').value);}
    function call(operation, data={}){return new Promise((resolve,reject)=>{if(!port)return reject(new Error(t('connecting')));const id=++serial;pending.set(id,{resolve,reject});port.postMessage({id,operation,capability,...data});});}
    async function refresh(){const previous=$('model').value;models=(await call('audio-generation.models')).items||[];options(previous);}
    const draft=()=>({schema:'ai2apps.mini-app-draft/v1',miniApp,model:$('model').value,prompt:$('prompt').value,lyrics:$('lyrics').value,duration:$('duration').value,seed:$('seed').value,steps:$('steps').value});
    async function save(){await call('draft.set',{value:JSON.stringify(draft())});}
    async function setup(){if(busy)return;busy=true;status='saving';$('error').textContent='';state();try{await call('setup',{installMore:true});await refresh();status=selected()?.ready?'ready':'setup';}catch(error){$('error').textContent=error.message;status='setup';}finally{busy=false;state();}}
    $('install').onclick=setup;$('model').onchange=()=>{if($('model').value===installOption){$('model').value=currentModel;void setup();}else modelChanged();};$('prompt').oninput=state;
    $('form').onsubmit=async event=>{event.preventDefault();if(busy||!selected()?.ready||!$('form').reportValidity())return;busy=true;cancelling=false;status='running';$('prepared-prompt').textContent=selected()?.preferredPromptLanguage==='en'?(locale==='zh'?'生成前会通过简单 Task 模型翻译并润色声音描述。':'The Simple Task model translates and polishes the description before generation.'):'';$('error').textContent='';state();try{await save();if(cancelling)throw new Error(t('cancelled'));const result=await call('audio-generation.generate',{payload:{model:selected().id,prompt:$('prompt').value.trim(),duration:Number($('duration').value),lyrics:selected().lyrics?$('lyrics').value:'',seed:Number($('seed').value),steps:Number($('steps').value)}});$('prepared-prompt').textContent=result?.preparedPrompt?(locale==='zh'?'实际生成提示词：':'Generation prompt: ')+result.preparedPrompt:'';status='complete';}catch(error){status=cancelling?'cancelled':'failed';if(!cancelling)$('error').textContent=error.message;}finally{busy=false;cancelling=false;state();}};
    $('cancel').onclick=async()=>{cancelling=true;state();try{await call('audio-generation.cancel');}catch(error){$('error').textContent=error.message;}};
    function accept(event){if(event.source!==window.parent||event.data?.type!=='ai2apps:studio-connected'||event.data.version!==1||!event.ports?.[0])return;window.removeEventListener('message',accept);port=event.ports[0];localize(event.data.locale);port.onmessage=event=>{if(event.data?.type==='ai2apps:studio-locale'){localize(event.data.locale);return;}const task=pending.get(event.data?.id);if(!task)return;pending.delete(event.data.id);event.data.error?task.reject(new Error(event.data.error)):task.resolve(event.data.value);};(async()=>{await refresh();const raw=await call('draft.get');if(typeof raw==='string'){const d=JSON.parse(raw);if(d.schema==='ai2apps.mini-app-draft/v1'&&d.miniApp===miniApp){for(const key of ['prompt','lyrics','duration','seed','steps'])if(typeof d[key]==='string')$(key).value=d[key];if(models.some(m=>m.id===d.model))$('model').value=d.model;modelChanged();}}status=selected()?.ready?'ready':'setup';state();})().catch(error=>{status='failed';$('error').textContent=error.message;state();});}
    localize(new URLSearchParams(location.search).get('locale')||'en');window.addEventListener('message',accept);window.addEventListener('load',()=>window.parent.postMessage({type:'ai2apps:studio-connect',version:1},'*'),{once:true});
    new ResizeObserver(()=>window.parent.postMessage({type:'ai2apps:mini-app-resize',version:1,height:document.documentElement.scrollHeight},'*')).observe(document.body);
})();
